spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vdane?characterEncoding=utf8&useSSL=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: mohensale
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
server:
  port: 8099